version: "3.5"

services:
    localstack:
        container_name: go-sqs-consumer-localstack
        build:
            context: ./localstack
            dockerfile: Dockerfile
        environment:
            - SERVICES=sqs
            - DEFAULT_REGION=eu-west-1
            - DEBUG=0
            - DATA_DIR=/tmp/localstack/data
        ports:
            - "4566:4566" # edge router
