version: "3.5"

services:
    go-sqs-consumer:
        image: go-sqs-consumer
        container_name: go-sqs-consumer
        build:
            context: .
        environment:
            - FOO=BAR
        ports:
            - "8080:8080"
